version: "3.9"

services:
  gunicorn:
    build: .

    restart: unless-stopped

    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app

  nginx:
    image: nginx:alpine

    restart: unless-stopped

    # Remove the exposed ports if using network bridge with reverse proxy
    ports:
      - 8000:80

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/src/app/static

    networks:
      - default
      # Use this for exposing nosferatu indirectly thought a reverse proxy
      # - proxy

# Overrides the default network of the compose stack, use this for exposing nosferatu indirectly through a reverse proxy

# networks:
#   proxy:
#     name: ${NETWORK_NAME}
#     external: true
