DROP TABLE IF EXISTS devices;

CREATE TABLE devices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip4 TEXT UNIQUE NOT NULL,
  mac TEXT NOT NULL,
  name TEXT NOT NULL
);